/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntregarRouteImport } from './routes/entregar'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as KitsRouteImport } from './routes/kits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregarRoute = EntregarRouteImport.update({
  id: '/entregar',
  path: '/entregar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entregar': typeof EntregarRoute
  '/entradas': typeof EntradasRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/kits': typeof KitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entregar': typeof EntregarRoute
  '/entradas': typeof EntradasRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/kits': typeof KitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entregar': typeof EntregarRoute
  '/entradas': typeof EntradasRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/kits': typeof KitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entregar' | '/entradas' | '/historial' | '/inventario' | '/kits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entregar' | '/entradas' | '/historial' | '/inventario' | '/kits'
  id: '__root__' | '/' | '/entregar' | '/entradas' | '/historial' | '/inventario' | '/kits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntregarRoute: typeof EntregarRoute
  EntradasRoute: typeof EntradasRoute
  HistorialRoute: typeof HistorialRoute
  InventarioRoute: typeof InventarioRoute
  KitsRoute: typeof KitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregar': {
      id: '/entregar'
      path: '/entregar'
      fullPath: '/entregar'
      preLoaderRoute: typeof EntregarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntregarRoute: EntregarRoute,
  EntradasRoute: EntradasRoute,
  HistorialRoute: HistorialRoute,
  InventarioRoute: InventarioRoute,
  KitsRoute: KitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
